### PR TITLE
Master

### PR DESCRIPTION
**Pull request by RoaddogLabs**
clean up gerber dir structure after adding rs format gerbers

### CODE REVIEW

**Comment by zerox1212** [comment]
Hello, this is the first PCB I have ever designed so I am curious what you changed here. Are you planning on producing this PCB? I have not made one yet and it isn't tested; also I'm a noob at this so the board itself is probably not a great design. Especially because I just have headers for the small HX711 PCBs. Ultimately the HX711s should be directly on the PCB.

**Comment by RoaddogLabs** [comment]
I think for now the carriers are a good way to get it off the ground.  I've got the docs from the Sparkfun carrier and was planning to use those to make a design that integrates the amps on a single board and uses a Pi ZeroW in a daughter card config.  Your board for use with the carriers is a great job for a first time board.

The availability of the NX711s from the big three suppliers in the US is non existent.  The issue with getting them from ebay or Aliexpress is they might be knock offs.  At this point better to go with something known or at least like Amazon where you have some recourse.   Kynix in Shenzhen has a couple hundred K in stock but a $10 parts minimum (this part is .40) and DHL starts at $35.  Once we get to the point of an integrated board I'll look at having 10 or so made by me in Vegas or at a PCBA in Shenzhen (you're going to hear Shenzhen a great deal, it's the center of the universe for electronics fab).

Right now though getting a working prototype up and going should be job 1.  The rest will come easily after that.  Best to show the guys at the SM forum something like this has legs.

**Comment by zerox1212** [comment]
I will update the PCB design this weekend so we can try a first rev. I also plan to use https://www.amazon.com/CHENBO-Weighing-Dual-Channel-Precision-Pressure/dp/B01D1FECVI/ref=sr_1_2?ie=UTF8&qid=1497622559&sr=8-2&keywords=hx711 instead of spark fun because they are way cheaper. I have to confirm the measurements as I'm not sure the PCBs are the same size. Keep your eye out for a new rev to be merged.

**Comment by RoaddogLabs** [comment]
The Amazon carriers are a great place to start, I'll order some myself.  It's the same sort reference circuit between the two.  There is a difference in the layout, the boards aren't populated the same.  It's not likely they are the same size.  I've used thousands of those sorts of parts from SZ.  They're mostly good depending on who makes them.  They're making more than 10k of those so the fab prices are well under a buck a unit.  

In a final design depending on the production scale it's going to be tough to beat using the generic carriers in terms of price.  For 8 bucks a set it's a screaming deal and that's including the US market mark up.   The entry level 3D printers used to use the same topology (a stepper motor shield on an Arduino where the drivers were on carriers on the shield)  The application scaled so that it made more sense to incorporate them onto a main board when tens of thousands of units started to be produced.  That's the main reason I stopped making and selling 3D electronics as I couldn't compete with even the small guys in SZ.   What you are doing with the scale project is very similar to what we were doing in the 3D printer space 5-6 years ago.

The Sparkfun docs I'll use as a starting point for the support circuit.  There is a basic circuit on the  NX711 datasheet as well.  I should have a rough BOM for a populated board in the next few days.  In the meantime once we validate the manufacturability of the new board (it should be fine, Fritzing is good like that) I'll get a set of boards going.

**Comment by zerox1212** [comment]
So just looking at the spark fun pcb here https://www.sparkfun.com/products/13879 it looks like the Fritzing model was the old version (before they split VCC and VDD). So actually there is a good chance the current PCB in Fritzing is correct for the Amazon boards. I will check the dimensions before publishing a testable PCB.

**Pull request closed without merging**
