### PR TITLE
Rev 02 of PCB

### PR DESCRIPTION
**Pull request by zerox1212**
Remove redundant power pins, add jumper pins for selecting HX711 channel

### CODE REVIEW

**Comment by zerox1212** [comment]
@RoaddogLabs Can you review this and let me know if the gerber files pass Seeed?

Unfortunately it's kind of difficult to measure precisely with Fritzing, but it does appear that these header positions will work for the cheap Amazon loadcell boards. They will NOT work for the "updated" SparkFun board. I will double check tonight and post here.

Other than that if you think it looks OK we could buy a few and see if they will work. Keep in mind you will need to also buy some header pins, some jumpers for channel selection, and a RPi 3 header.

**Comment by zerox1212** [comment]
After more detailed measurement I have to adjust the design. The amazon amps are 20.25mm center to center on each row of headers. The current one is 25.5mm center to center.

**Comment by zerox1212** [comment]
I had to make a custom Fritzing part for this to work. It isn't almost finished, but the PCB layout has an issue for some reason.

**Comment by zerox1212** [comment]
I'm struggling to get my custom Fritzing part to work. Might be better to remake this board in Eagle...
http://forum.fritzing.org/t/svg-circles-dont-match-fritzing-circles/4005/2

**Comment by RoaddogLabs** [comment]
I'll give it a look and get something generated in Eagle.

**Comment by zerox1212** [comment]
I'll try one last time to make it work today. I received some good advice from the Fritzing forum.

**Comment by RoaddogLabs** [comment]
Give it a shot.  I generated one in Eagle last night but I haven't yet pushed it.   Here's a screen cap of the board. [pi-hat-v.01.pdf](https://github.com/jenkinsracing/open-race-scale/files/1092297/pi-hat-v.01.pdf)  I still need to make the nets from the carriers to the header and tighten the distance between the carrier headers.  I've changed the orientation of the carrier headers to accommodate the spec hat board size.  Hat specs from RPi Foundation at  https://github.com/raspberrypi/hats

Using the current Fritzing layout there is going to be an issue with the hat board clearing the usb and ethernet connectors.  It's going to at least take a longer GPIO header to clear and I'm not sure about any noise or heat over the ports on the Pi though I would think it would be minimal.  I haven't yet sourced the longer header but the pin pitch is a tighter than a standard 2.54 mm. Boards that don't at least dimensionally conform to the spec legally can't be called "Pi Hats" but doubt anyone will pursue it given the low volumes.  Best practice would be keeping to the Pi spec for hats.

**Comment by zerox1212** [comment]
I have solved the issue and made a new PCB. The carriers should match the 5 pack of Chenbo XFW-HX711 sold on Amazon for $8.

This PCB would require this header: https://www.adafruit.com/product/1979

I fully support making a better Pi Hat and doing it in Eagle as Fritzing is kind of a pain. For example if we changed from the Amazon PCB to Spark Fun, I basically have to redraw all the nets on each view (breadboard, schematic, pcb). However, I also want the load cell connectors to be convenient. Something like this is what I had in mind: https://www.amazon.com/dp/B00QC6QS5W/ref=cm_sw_r_cp_dp_T1_4QRszb7ZK64BP . Even better if you can find a way to delete the channel jumpers, and just fit 4x six terminal connectors.

Please review this PCB and see if it's ready for a small batch to test.

**Comment by RoaddogLabs** [comment]
The gerbers and drill file look fine in the Seeed viewer, here's the overview.
open-race-scalev1r2proof

The connectors to the scale pads are known by some as "euro blocks".  Technical name plugable terminal blocks.  The application is typically higher current circuits.    In onesy-twosy they'll be $4-5 per mating pr for brand name.  The generics are much less but suffer from stripping screws and the inserts failing.  We use this style quite a bit on the printer boards for hot ends, fans and heated beds.  Here's a TE datasheet.  http://www.mouser.com/ds/2/418/NG_CD_796693_B2-633930.pdf

**Comment by zerox1212** [comment]
If you have a better idea to terminate the loadcells I'm open to it. For now this should be easiest for testing. Merging.

**Comment by RoaddogLabs** [comment]
There are a set of boards on the way.  Should be 7-10 days.

**Comment by zerox1212** [comment]
Email me at andrewj@zeroentity.com so I can find a way to send you some money to get a couple of the PCBs. Also have not actually tested the software with 4 LC amps and loadcells, so you will have to make bug reports. Chances of it working with the current rough software is slim. Thanks.

**Comment by RoaddogLabs** [comment]
I'll pick up the tab on these.  I'll send you half of them when they get in.  It's usually 10 though could be as few as 9 or as many as 12.

**Pull request merged**
